### ISSUE TITLE
To-Do List Scroll not there

### ISSUE THREAD

**Issue by jamazon007** [t9tio/tomato-pie#10]
I often have dozens of assignments to put in to-do list, but I cannot scroll down to add any more after I reach the bottom of the screen.

**Comment by timqian** [comment]
@jamazon007 Thanks for pointing this out, scrolling has been enabled. The extension should be auto-updated from chrome web store within 6 hours.

![Kapture 2019-03-30 at 16 33 05](https://user-images.githubusercontent.com/5512552/55273697-97e9be00-5309-11e9-85f6-f41857023c9d.gif)

When there are too many todos, the UI did not look well though, I am planning to improve the layout soon, stay tuned~

**Comment by jamazon007** [comment]
Thank you so much for the timely response and fix!
