### ISSUE TITLE
hyperlinks parsing

### ISSUE THREAD

**Issue by obar1** [t9tio/tomato-pie#16]
tomatoes task don't support any html it's just **text**
it would be nice that to make a bit more clever
so ex

copy and paste of 
`https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=1nj101dboqm98&search=inbox&th=%23thread-f%3A1645464651883008412&cvid=2`
to be rendered as hyperlink where I can click and get the page

**Comment by timqian** [comment]
Thanks for the suggestion @obar1 This feature is implemented in v2.7 https://github.com/t9tio/tomato-pie/tree/master/blog#2019-10-22-hyperlinks-parsing
