### ISSUE TITLE
可以考虑引入不同的"主题"布局吗?

### ISSUE THREAD

**Issue by lsby** [t9tio/tomato-pie#21]
感谢这个应用,todo列表和可以随手记文件的文本区非常贴心.
工作上我经常要复制一些关键信息备用,这个文本区我非常喜欢.
但我觉得文本区太小了,相反,时钟对我来说意义不大,即使是纯数字的时钟我也不介意.

我看到的效果是这样:
![image](https://user-images.githubusercontent.com/7814085/93352379-589c8d80-f86d-11ea-8258-980bfec70db4.png)

文本区只有右边一点点,复制的东西一多就难以翻找.

可以考虑引入不同的"主题"布局吗?
例如,A主题是目前这样,B主题是一个全屏的文本编辑器,只有右上角显示时间,C主题又是其他...

如果您不反对这个想法,我会提交一些pr.

另外:"Default tab"选项似乎有问题,关闭后,默认标签会变成系统默认标签,而我期待关闭后会使用我原有的默认标签页扩展.

**Comment by timqian** [comment]
我觉得能让用户选择不同的主题，是一个不错的想法。欢迎PR。不过这个扩展的实现上不是那么优雅，可能需要设计一下怎么样来支持不同主题的布局会比较好。你可以试一下。即使最后我们这个工具的想法不一样，你也可以fork一个新的版本，发布到Chrome web Store。

关于关闭 default tab 选项，这是Chrome Extension的限制，可能不是很好解决。
