### ISSUE TITLE
Is it possible to pause the timer(cancel current pomodoro)?

### ISSUE THREAD

**Issue by NileDaley** [t9tio/tomato-pie#7]
Is there a way to pause the timer? 

If not, would it be possible to add a way to pause the timer or cancel the current pomodoro?

**Comment by timqian** [comment]
Currently the only way to abandon current tomato is start another. I think tomato cancellation or deletion is a necessary feature too. I will try to add it in the next release.
About pausing timmer, it seems not the way to do pomodo, so it might not be added in near feature

**Comment by timqian** [comment]
Abandon tomato feature is implemented in 2342e080de9493f18f023dc749f3c7180b1df42d
and is pushed chrome webstore. Have a try
![Kapture 2019-03-14 at 0 20 19](https://user-images.githubusercontent.com/5512552/54297502-fd436c80-45f1-11e9-8a91-8804976263a3.gif)
