### ISSUE TITLE
Is possible to use it without the new page override ?

### ISSUE THREAD

**Issue by cormil** [t9tio/tomato-pie#8]
To use the extension seems that I have to change the new page.
Is possible to use it with the icon only and use my usually new page ?
thanks

**Comment by timqian** [comment]
thanks for trying tomato-pie, this feature is in my the plan, stay tuned

**Comment by timqian** [comment]
After doing some search, I find 2 ways to enable user deciding whether he/she wants to override new page with tomato-pie:
1. [Manually change update page url to extension url when new tab is created](https://stackoverflow.com/a/30439347/4674834)
    problem: In this way, URL of the extension will appear in the Omnibox, which is not convenient for user to do search or input new URL.
2. [Redirect user to chrome-search://local-ntp/local-ntp.html and chrome will open default new tab.](https://stackoverflow.com/a/33947304/4674834)
    problem: In this way, the new tab is still controlled by tomato-pie, user can not use other new tab extension, another small issue is for firefox user this introduce a bug(I don't know if there are firefox users though)

The second way sounds better to me for now as the first solusion seems bringing more trouble than convineance, so I will implement second way first. And let's keep this issue open to see if we have better way to handle this problem

**Comment by timqian** [comment]
The change has been pushed and normaly after no longer than 6 hours, the extesion will auto updated. now you can turn off the default beheavior in the setting. try in the extension
<img width="240" alt="Screen Shot 2019-03-12 at 5 13 17 PM" src="https://user-images.githubusercontent.com/5512552/54188212-30023d80-44ea-11e9-98df-5e9ad74086d1.png">
